{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rtylr.secretName" . }}
  labels:
    {{- include "rtylr.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ required "secrets.jwtSecret is required (or set secrets.existingSecret)" .Values.secrets.jwtSecret | quote }}
  INTERNAL_TOKEN: {{ .Values.secrets.internalToken | quote }}
  CDN_API_KEY: {{ .Values.secrets.cdnApiKey | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  {{- if not .Values.license.existingSecret }}
  RTYLR_LICENSE_KEY: {{ .Values.license.key | quote }}
  {{- end }}
  {{- range $k, $v := .Values.extraSecretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
